require("./libs/pools")
require("./libs/copyWorldPosRot")
require("./libs/ensureElement")
require("./libs/touchGestures")
require("./libs/betterRaycaster")

addEventListener('DOMContentLoaded', e => {
  document.body.addEventListener("swipeup", e => {
    document.body.requestFullscreen()
  })
})

require("./components/aframe-state-component")
require("./states/states")
require("./components/htmlembed")
require("./components/aframe-orbit-controls-component")
require("./components/classeroomdeskchair")
//require("./components/ReCITgrabbing")
//require("./systemm/recitgrab")
require("./components/grabbing")
require("./components/include")
require("./components/scienceslab/injectglasses")
require("./components/arealight")
require("./components/injectfluo")
require("./components/recitpreloader")
require("./components/injectglove")
require("./components/injectplayer")
require("./components/scienceslab/injectbeaker")
require("./components/scienceslab/injectpince")
require("./components/scienceslab/injectpipette")
require("./components/scienceslab/injectreagent")
require("./components/scienceslab/injecttesttube")
require("./components/scienceslab/injecterlenmeyer")
require("./components/scienceslab/injectcylindergraduate")
require("./components/limit")
require("./components/injectwalls")
require("./components/injectflashlight")
require("./components/classeroomdeskchair")
require("./components/locomotion")
require("./components/onevent")
require("./components/onstate")
//require("./components/aframe-state-component")
require("./components/physics")
require("./components/script")
require("./components/trigger")
//require("./components/aframe-websurfaces.umd")
require("./primitives/a-classroom")
require("./primitives/a-reagent")
require("./primitives/a-pince")
require("./primitives/a-pipette")
require("./primitives/a-glasses")
require("./primitives/a-fluorescent")
require("./primitives/a-flashlight")
require("./primitives/a-beaker")
require("./primitives/a-testtube")
require("./primitives/a-cylindergraduate")
require("./primitives/a-erlenmeyer")
require("./primitives/a-glove")
require("./primitives/a-hand")
require("./primitives/a-main")
require("./primitives/a-player")
require("./primitives/a-laboratory")
require("./primitives/a-html")
require("./systems/laboratory")
//require("./systemms/recitgrab")

const pkg = require("../package")
console.log(`${pkg.title} Version ${pkg.version} by ${pkg.author}\n(${pkg.homepage})`)
